---
title: "Gov 50 Final Project"
author: "McGavock Cooper"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the analysis of various polls, and what factors may cause a poll to be more or less accurate. 


For my research question I want to determine if geography and type of institution, such as a college or a news organization, can influence the accuracy of the conducted polls. I am using 538's poll ratings and detail as my data set. I hypothesize that polls run by institutions originating in places that lack political diversity or are dominated by one party will be slightly less accurate than polls conducted from more moderate political geography, and I hypothesize that colleges and other insitutuons will be less accurate than news organizations. The explanatory variable of interest would be political geography and then the "level" of institution, educational or from the media. The outcome variable of interest would be the difference between the accuracy the different groups of polls. If media polls in more moderate or diverse areas are more effective in reflecting the eventual outcome, I will conclude that these polls are more useful to determine elections. 


## Graphs:
```{r data, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)

data <- read.csv("./pollster-ratings.csv", header = TRUE, stringsAsFactors = FALSE)
p <- ggplot(data, aes(x=`Bias`, y=`Races.Called.Correctly`)) + 
  geom_point() + 
  theme_minimal() + 
  labs(title = "Bias effect on Races Called Correctly", x="Bias",y="Races Called Correctly")
print(p)
```
